const { withXcodeProject } = require('@expo/config-plugins');

/**
 * Xcode's "User Script Sandboxing" (ENABLE_USER_SCRIPT_SANDBOXING) restricts what paths a Run
 * Script build phase may write to. CocoaPods' generated "[CP] Copy Pods Resources" phase writes
 * `ios/Pods/resources-to-copy-<target>.txt` without declaring it as a script output, so with
 * sandboxing on, the write is denied and the build fails with:
 *   error: Sandbox: bash(...) deny(1) file-write-create .../Pods/resources-to-copy-*.txt
 *
 * `ios/` is regenerated by `expo prebuild`, so the fix has to be applied here rather than by
 * hand-editing the generated project.
 */
module.exports = function withDisableUserScriptSandboxing(config) {
  return withXcodeProject(config, (config) => {
    const buildConfigurations = config.modResults.pbxXCBuildConfigurationSection();
    for (const key in buildConfigurations) {
      const buildSettings = buildConfigurations[key]?.buildSettings;
      if (buildSettings) {
        buildSettings.ENABLE_USER_SCRIPT_SANDBOXING = 'NO';
      }
    }
    return config;
  });
};
